CAT_DICT = {
    'no category': '',
    'aan het infinitive': 'ahi',
    'adjectival phrase': 'ap',
    'adverbial phrase': 'advp',
    'bare infinitival phrase': 'inf',
    'complementizer phrase': 'cp',
    'coordinate phrase with conjunction': 'conj',
    'coordinate phrase without conjunction': 'list',
    'determiner phrase': 'detp',
    'discourse unit': 'du',
    'free relative': 'whrel',
    'main clause wh-question': 'whq',
    'main clause(SVO)': 'smain',
    'multi word unit': 'mwu',
    'noun phrase': 'np',
    'om te infinitive': 'oti',
    'past participial phrase': 'ppart',
    'prepositional phrase': 'pp',
    'present participial phrase': 'ppres',
    'relative clause': 'rel',
    'root of a dependency structure': 'top',
    'subordinate clause wh-question': 'whsub',
    'subordinate clause(SOV)': 'ssub',
    'te infinitive': 'ti',
    'van clause': 'svan',
    'verb initial clause(VSO)': 'sv'
}

POS_DICT = {
    'adjective': 'adj',
    'adverb': 'adv',
    'complementizer': 'comp',
    'comparative': 'comparative',
    'determiner': 'det',
    'fixed parts': 'fixed',
    'named entity': 'name',
    'noun': 'noun',
    'numeral': 'num',
    'particle': 'part',
    'pronominal adverb': 'pp',
    'pronoun': 'pron',
    'preposition': 'prep',
    'punctuation': 'punct',
    'tag': 'tag',
    'verb': 'verb',
    'conjunction': 'vg'
}
